# Navigation Links

main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 30
  - name: Teaching
    url: /teaching/
    weight: 40
  - name: Lab
    url: /lab/
    weight: 50
  - name: Software
    url: /software/
    weight: 60
  - name: Data
    url: /data/
    weight: 70
  - name: News
    url: /blog/
    weight: 80
