---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<h3 style="text-align: center;" markdown="1">Quantitative Political Methodology</h3>
<h3 style="text-align: center;" markdown="1">L32 363</h3>

#### Class information

##### Lecture
Monday and Wednesday  
1:00 -- 2:00  
Seigle Hall 304

##### Labs

Seigle Hall L016  
Lab A: Thursday 9:00--10:00  
Lab B: Thursday 10:00 -- 11:00  
Lab C: Friday 9:00 -- 10:00  
Lab D: Friday 10:00 -- 11:00  


#### Instructor Information

Jacob M. Montgomery, Ph.D.  
Associate Professor, Department of Political Science  
**Office**: Seigle 285  
**E-mail**: jacob.montgomery@wustl.edu  
**Office Hours**: Tues. 1:30-3:30 and by appointment 



#### Textbooks/Readings

Alan Angresti and Barbara Finlay.  2009.
*Statistical Methods for the Social Sciences, Fourth Edition*.
Upper Saddle River, NJ: Prentice Hall.  ISBN: 978-0130272959

James E. Monogan III. 2015. *Political Analysis Using R*. New
York: Springer. ISBN 978-3-319-23446-8  (An online version of this
book is available for free through Springer Link in library)

See the [Online Course Book](http://jmontgomery.github.io/PS363CourseBook/) for additional reading materials.

#### Software

You will be using the R statistical package
(http://www.r-project.org/). This package is widely used in
political science, economics, psychology, sociology, and
biostatistics. R is available for every computing platform, and most
importantly, is free. As such, you need not rely on computer labs to
complete your assignments. Please feel free to contact Professor
Montgomery or a TA if you have any questions about software.
_Please bring your laptops to the first lab session for help
  installing the program._

____________
____________


#### Course description

We are on the doorstep of a new era of social science. Never before have political scientists had access to so much data
about the attitudes and actions of individuals, institutions, and
nations.  Data on everything from the [votes of members of the
U.S. Senate in 1855](https://voteview.com/search/?congress=34) to [terrorist attacks from around the globe](http://www.start.umd.edu/gtd/) are
only a few clicks away.
 
This class is designed to make you an active participant in this new
data-rich world.  The goal is to introduce you to the methods and
practices by which you can use this data to answer questions that are
important to us as political scientists and citizens.  What policies
are most effective at reducing poverty?  Which campaign ads are most
effective at persuading voters?  Can we affect the behavior of our
Facebook friends just by sharing our opinions?
 
The purpose of this class is to teach you how to use data to answer
these kinds of questions.  This class will introduce you to the
theoretical concepts you need to test claims about the political world
and the practical skills you will need to conduct and present
statistical analyses.
 
Although students will certainly be expected to engage with
mathematics, formulas, and data analysis, the goals of the class are
primarily conceptual rather than narrowly mathematical. The course
will focus on helping students to understand the core concepts behind
statistical tests, understand their uses (and limitations), learn to
apply them appropriately to substantive problems of interest, and
learn how to communicate findings to others.  In addition, a major
component of the course include learning how to collect, manage, and
analyze data using computer software, and how to effectively
communicate results to others.


#### Learning objectives

By the end of this course, you should be able to:

- Present data using graphics and descriptive statistics in a clear and informative manner
- Apply basic concepts from probability theory to social science research questions
- Describe the threats to making causal inferences from observational data and identify how they could change the conclusions of a study
- Make inferences about the distribution of populations based on a sample 
- Correctly conduct and interpret hypothesis tests
- Understand linear regression in theory and practice (i.e., be able to read and interpret regression tables in academic articles)
- Work collaboratively with other students to complete problem sets that apply concepts from class readings and short lectures
- Independently gather, analyze, interpret, and present your own data

____________
____________


#### Assistants to instructor

There are three graduate and two undergraduate assistant to instructor. The graduate students concentrate
in social science or applied statistics and have vast experience in applied quantitative analysis.  The undergraduate teaching assistants have successfully completed this course.  

Each laboratory session will be led by one of the  graduate assistants to instructor. Most grading will be done by the graduate students; some will be done by Professor Montgomery.  The graduate assistants to instructor will work closely in conjunction with Professor Montgomery on all issues of grading. I encourage you to get to know the assistants to instructor responsible for your lab.

##### Graduate ATIs (office hours and location)

Taishi Muraoka| Erin Rossiter| Min Hee Seo   
-----|-----|-----|-----|-----|
tmuraoka@wustl.edu| erinrossiter@wustl.edu|  minheeseo@wustl.edu     
 Seigle 274 | Seigle 277 | Seigle 258
Tuesday 3:00-5:00 | Friday 3:15-5:15 | Monday 3:00-5:00

##### Undergraduate ATIs (office hours and location)

Cara DiLiberti| Joe Ludmir
-----|-----
cdiliberti@wustl.edu| jludmir@wustl.edu
Cafe Bergson | Cafe Bergson
Tuesday 4:00-6:00 | Tuesday 6:00-8:00
Thursday 5:00-6:30 | Thursday 5:00-6:30


____________
____________


#### Team Based Learning

This course will feature as little traditional lecturing as I can manage while still ensuring you understand the materials. Students will be expected to learn the basic content of the readings before class so that the majority of class time can be dedicated to discussion, group work, and hands-on demonstrations, which are more likely to facilitate successful learning. We will work in teams throughout the semester to maximize active engagement with the course material. By working in teams, students will not only develop communication and collaboration skills but assist each other in understanding and applying concepts successfully. Early in the semester, you will be assigned to a team of five students.  You will work with this team throughout the semester on both in-class assignments and your final research project. To ensure that each student contributes the group's success, your contributions will be assessed via the self- and peer-evaluation components discussed below.

____________
____________


#### Requirements and Evaluation

Grading in this class will be based on the components described
below. *Late work will not be accepted without prior
  permission*. Makeup exams will not be given, and students who miss
exams will receive a score of 0 absent extraordinary circumstances.

If you get | you get an
-----|-----
$\ge$ 94| A| 
$\ge$ 90 | A-  
$\ge$ 87 | B+ 
$\ge$ 83| B| 
$\ge$ 80 | B- 
| $\ge$ 77 | C+ |
$\ge$ 73|  C| 
$\ge$ 70 |  C-
 $\ge$ 67 |  D+ 
$\ge$ 63| D 
$\ge$ 60 | D- 
$<$ 60 | Fail



##### Peer assessments - 10%

Early in the semester, you will be assigned into a team of 4-6
individuals.  You will work with this team throughout the semester on
in-class assignments and your final research project.  To help ensure
that all members of the team are actively contributing, students will
be asked to evaluate their teammates' contributions, effort, and
performance.  You will receive ungraded midterm evaluations from your
group to help you know how well you are doing and identify areas in
need of improvement. You will also complete a midterm self-evaluation
of your own contributions, effort, and performance using an identical
form to help you reflect on your own effort and performance. (All peer
and self-evaluation forms are provided at the end of the syllabus.)



##### Problem sets, in-class work, and quizzes - 20%

###### Problem sets

*Problem sets*, or homeworks, will be distributed
throughout the course (10%). These are individual assignments that you
should prepare yourself, though you may ask your colleagues for
help. Please turn them in at the on the specified date **at the
  beginning of class** with only your WUSTL ID number (i.e., not your
name) written in the space provided. If you have a printing problem,
you are responsible for emailing it to your graduate TA before class
starts.  Each student's lowest homework grade will be dropped in
the final grade calculations.  This option should be reserved for
illness, family emergencies, broken alarm clocks, or other unforeseen
events.  No additional waivers will be granted.

###### IPAs

*Individual preparedness assessments* (IPAs) are open
book quizzes that will be take using R
before each class (5%). They will be posted at least 24 hours before they are due and are available and must be completed before class begins. Note that the specific time when your IPA is completed will be reported along with your score, so late tests will not be graded.

IPAS are designed to ensure that students arrive to class
prepared to engage in discussion and team activities based on the
assigned reading.  (Many in-class team activities will be graded, so
these assessments are necessary to ensure that all members are ready
to contribute.)  You should complete these assessments yourself with
no assistance from your colleagues; you may not discuss them with
other students prior to class.  Each student's two lowest IPA grades
will be dropped in final grade calculations.  This option should be
reserved for illness, family emergencies, broken alarm clocks,
computer crashes, or other unforeseen events.  No additional waivers
will be granted.

*Note*: We are trying a new system for IPAs using R (and moving away from the horrible Blackboard system). Additional details about how these IPAs will be posted and graded will be discussed in detail later in the class.  This section of the syllabus will be updated at that time.

###### In-class assignments

*In-class assignments* will be completed during class
with your research team (5%).  All members will turn in a single
assignment at the end of class and will share their grade. However,
**all absent students will receive a zero**; any attempt to
include an ID number for an absent student will be considered an
academic integrity violation. Students missing more than five minutes
of class time will be counted as absent.  Each student's two lowest
in-class assignment grades will be dropped in the final grade
calculations.  This option should be reserved for illness, family
emergencies, broken alarm clocks, or other unforeseen events.  No
additional waivers will be granted.

##### Midterm exam - 20%

The midterm exam will be held in class on October 11th and will cover
the material discussed in class up to that point. Students will be
provided with relevant statistical tables and are allowed to use a
calculator with no information stored in memory.



##### Research project - 25%

Working with your assigned team, students will select a social science
research question of interest, collect data, and conduct a
quantitative analysis of their results. These findings will be written
up and presented as scientific posters during the final lab
periodÏ. Each group should submit a Powerpoint or PDF file of their
poster and replication data/annotated R code generating your results
*before the final lecture period on December XX.*

- Don't worry about whether your hypothesis was supported!  Evaluation will
  be based on the criteria specified in the rubric on the final page
  of this syllabus, not the statistical significance of your results.
- Teams receiving the best poster grades are inevitably
those that start early and those teams that come to me early and often
to *me* for feedback.
- There will also be an optional ``poster session" (location/date TBD).  The best poster
in each section as selected by Political Science Department faculty
will receive 1% extra credit toward their overall course
grade.





##### Final exam - 25%

A comprehensive final exam will be held December 20th at 1:00PM - 3:00PM. Students will be provided with relevant statistical tables and are
allowed to use a calculator with no information stored in memory.


##### Extra credit

**No adjustments will be made to final grades under any circumstances.**
Students will have the opportunity to earn extra credit over the
course of the semester to provide an extra cushion in case of lazy
team-mates, a malfunctioning calculator, or unusual anxiety during
finals due to the opening of the Chamber of Secrets, an attack by
rogue dementors, the sudden death of the Headmaster, or the return of
You Know Who.

- As noted above, the team that earns the most votes for the best research poster will earn 1%.  
- Students can also increase their final grade 1% by completing their official online course evaluations for both Professor Montgomery and assistants to the instructor for their lab.  
- Students may earn up to another 1% for creating a video tutorial or other online content to be added to the course website. The topic of this video must be approved in advance, and the final product must be delivered to me before the final exam. 

____________
____________

#### Class policies


##### Grade Appeals

I am happy to meet with students about grading issues, but only after
they have met with their graduate assistant to the instructor. Please meet first
with the leader of your lab with any concerns about evaluation.

If you wish to appeal the grading of an exam or assignment, you must
return it to either me or an assistant to the instructor within 72 hours of the time when the graded assignment is returned to the class or your section. Assignments returned on Thursday or Friday
must be returned by Noon on the following Monday.  You must staple to
the original graded exam or assignment a note that states which
question(s) is (are) to be re-graded and why you believe that your
answer deserves more credit. Nothing additional (notes, explanations,
etc.) should be written on the original assignment and NO changes or
erasures should be made on the original before regrading.  A
percentage of all written assignment are photocopied and compared to
the regrade requests. Cheating will not be tolerated.

##### Technology in the classroom

You will frequently make use of computers in this course, during some
lecture periods and during every lab.  Please be respectful to your
instructors and your peers by using your computers only for
class-related purposes.  Please put your phone away before class starts and
don't bring it out.

##### Academic Honesty

Cheating and plagiarism will not be tolerated.  I strongly encourage
you to review the University's policies regarding academic honesty,
which you can read at:
http://www.wustl.edu/policies/undergraduate-academic-integrity.html.

In general, if you have any question, please feel free to ask
your lab leader or Professor Montgomery. Specific rules for this course:

- You may work together on homework in small groups, but you
  should each prepare your answers separately.
- The homeworks and in-class work are open book and open
  notes.  However, you *may not* make use of answer keys or
  graded assignments provided by students from previous years for
  either homeworks or in-class assignments.
- You are to consult *only* with Professor Montgomery or
  a TA during exams.
- You will be allowed to bring one sheet of paper to exams to
  consult.  This may be filled (front and back) with any equations or
  notes you may find helpful.  Otherwise the exams will be closed
  book.
- Graphic calculators are allowed during exams, but the memory
  must be cleared. Students should be prepared to show a confirmation
  of a cleared memory at the beginning of the exam.

All cases of cheating or plagiarism will be referred to Washington
University's Committee on Academic Integrity. If the Committee on
Academic Integrity finds a student guilty of cheating, then the
penalty will be (without exception) automatic failure of the course.

##### Students with disabilities

Students with disabilities enrolled in this course who may need
disability-related classroom accommodations are encouraged to make an
appointment to see me before the end of the second week of the
semester.  All conversations will remain confidential. Please also
arrange to have the required documentation sent to me for any
accommodations *at least two weeks prior to the first exam.*


##### Religious observances

Some students may wish to take part in religious observances that
occur during this semester. If you have a religious observance
that conflicts with your participation in the course, please meet with
me *before the end of the second week of the semester* to discuss
accommodations.

##### Accommodations based upon sexual assault

The University is committed to offering reasonable academic accommodations to students who are victims of sexual assault.  Students are eligible for accommodation regardless of whether they seek criminal or disciplinary action.  Depending on the specific nature of the allegation, such measures may include but are not limited to: implementation of a no-contact order, course/classroom assignment changes, and other academic support services and accommodations.  If you need to request such accommodations, please direct your request to Kim Webb (kim_webb@wustl.edu), Director of the Relationship and Sexual Violence Prevention Center.  Ms. Webb is a confidential resource; however, requests for accommodations will be shared with the appropriate University administration and faculty.  The University will maintain as confidential any accommodations or protective measures provided to an individual student so long as it does not impair the ability to provide such measures.

If a student comes to me to discuss or disclose an instance of sexual assault, sex discrimination, sexual harassment, dating violence, domestic violence or stalking, or if I otherwise observe or become aware of such an allegation, I will keep the information as private as I can, but as a faculty member of Washington University, **I am required to immediately report it to my Department Chair or Dean or directly to the University’s Title IX Coordinator**.  If you would like to speak with the Title IX Coordinator directly, Ms. Jessica Kennedy can be reached at (314) 935-3118, jwkennedy@wustl.edu, or by visiting her office in the Women’s Building.  Additionally, you can report incidents or complaints to Tamara King, Associate Dean for Students and Director of Student Conduct, or by contacting WUPD at (314) 935-5555 or your local law enforcement agency.  

You can also speak confidentially and learn more about available resources at the Relationship and Sexual Violence Prevention Center by calling (314) 935-8761.



____________
____________


##### Tentative Schedule

**NOTE:** Below is a tentative schedule of assignments.  Please note that this is subject to change. Only assignments through 9/6 are firm at this point.  There will be assigned readings/online tutorials before every class session.

Date| Topic | Reading | Assignments| Notes
----------|------------|-------------------|-----------------|---------------|
8/28| Introduction <br> Class overview| AF: Chapter 1 <br> CB: Chapter 1 | |
8/30| NO CLASS <br> APSA Conference | | | [PS1 Distributed](http://jmontgomery.github.io/ProblemSets/PS1.pdf)
8/31-9/1| Introduction to R | Monogan: Chapter 1 <br> CB: Chapters 2-3 | |Lab
9/4| NO CLASS <br> Labor Day | | | |
9/6| Measurement <br> Sampling <br> Bias | AF: Chapter 2 <br>  CB: Chapters 4-6 |  |
9/7-9| Plotting in R <br> Opening data in R <br> Subsetting in R| Monogan: Chapters 2-3 <br> CB: Chapters 7-8 || Lab
9/11| Descriptive statistics | AF: Chapter 3 <br>CB: Chapters 10-11 |  |
9/13| Basics of probability | AF Chapter 4  <bf> CB: Chapter 12| PS1 Due | [PS2 Distributed](http://jmontgomery.github.io/ProblemSets/PS2.pdf)
9/14-15| Describing data <br> Data Types | Monogan Chapter 4 <br>  CB: Chapter 13 | | | Lab
9/18| Sampling distributions  | AF: Chapter 5 <br> CB: Chapters 14-15 |IPA (In class) | **Bring laptops**
9/20| Working with probability distributions | CB: Chapters 16-18 |IPA
9/21-22| Working with data
9/25| Confidence intervals <br> describing a population || IPA
9/27| Hypothesis testing intro || PS2 Due | PS3 Distributed
9/28-29| Confidence invervals 
10/2| Null hypothesis testing | |IPA
10/4| Poster discussion || PS3 Due | PS4 Distributed
10/5-6| Functions in R (NHP)
10/9| Exam review
10/11| Midterm
10/16| NO CLASS <br> Fall Break
10/18| Causality 
10/19-20| Advanced plotting
10/23| Experiments: Comparing means | | IPA
10/25| Experiments: Contingency tables || PS4 Due | PS5 Distributed
10/26-27| T-tests <bf> Tables
10/30| Regression and prediction 
11/1| Regression and inference || PS5 Due | PS6 Distributed
11/2-3| Regression in R
11/6| Interactions and dummies || IPA
11/8| Multiple regression || PS5 Due | PS6 Distributed
11/9-10| Multiple regression
11/13| Difference in differences || IPA
11/15| Regression discontinuity || PS6 Due | PS7 Distributed
11/16-17| DID and RD
11/20| Instrumental variables
11/22| NO CLASS <bf> Thanksgiving
11/27| Model fit | |IPA
11/29| Regression diagnostics | | PS7 Due | PS8 Distributed
11/30-31| Diagnostics in R
12/4| Slack/catch up
12/6| Exam review | | PS8 Due 
12/7-8| Poster presentations
12/20| Final Exam 1:00-3:00pm


____________
____________


#### Poster rubric (40 points total)

Score| 5| 4| 3| 2
-----|-----------------------------|-------------------------|-------------------------------|--------------------------
Introduction and theory| Precisely identifies null and alternative hypotheses and provides strong substantive and theoretical motivations for research project| Identifies null and alternative hypotheses and provides substantive and theoretical motivations for research project| Hypothesis described but null and/or alternative hypotheses not precisely or correctly specified; substantive and theoretical motivations incomplete or unconvincing| Theory incorrectly or vaguely stated; lacks appropriate substantive and/or theoretical motivation
Methods| Specifies all important aspects of how study was conducted in detailed and replicable fashion; convincingly motivates and defends key choices in design process| Specifies most important aspects of how study was conducted in relatively clear manner; addresses possible concerns about key choices in design process| Specifies some important aspects of how study was conducted; methods not always well-explained; does not sufficiently address possible concerns about  choices in design process.|Does not provide or clearly explain most important aspects  of how study was conducted; lacks appropriate justification of key design choices
Results| Figures and tables illustrate findings in an intuitive and easy-to-understand way; text explains results precisely and without statistical errors; investigation of hypothesis thorough and detailed| Figures and tables illustrate findings reasonably clearly; textual explanations of results is clear; statistical approach largely correct and error-free| Figures and tables unappealing or poorly constructed; some imprecision or errors in textual discussion of results; hypotheses not thoroughly investigated| Figures and tables  sloppy or hard to understand; text vague or incorrect; statistical errors in analysis; cursory investigation of hypotheses
Limitations and conclusions| Perceptive and detailed discussion of limitations of findings, potential explanations for those findings, substantive and theoretical conclusions, and possible future research| Clear and thoughtful discussion of limitations of findings, potential explanations for those findings, substantive and theoretical conclusions, and possible future research| Some useful discussion of limitations of findings, potential explanations for those findings, substantive and theoretical conclusions, and possible future research| Vague, incomplete, or unconvincing discussion of limitations, implications, and conclusions
Statistical analysis (poster)| Innovative use of statistical methods  to answer research question; no errors in statistical analysis| Correct use of statistical methods  to answer research question; no or few errors in statistical analysis| Potentially problematic use of statistical methods  to answer research question; some errors in statistical analysis| Flawed use of statistical methods  to answer research question; significant errors in statistical analysis
Statistical analysis (R script)| Replicates poster findings exactly from original data; clear, descriptive, and precise comments; correct and error-free statistical analyses and use of  R| Statistical analysis and R code are largely correct; comments relatively clear and descriptive| Some errors in statistical analysis or R code; failure to fully replicate poster or provide appropriate comments| Does not replicate poster; lacks comments; many statistical and/or R errors
Graphical design| Exceptionally attractive design and layout; free of formatting problems| Attractive design and layout; no or few formatting problems| Somewhat attractive poster; some formatting problems| Difficult-to-read or messy poster design; many formatting problems
Writing quality| Exceptionally well-written---precise, clear, and mistake-free; concise and elegant| Very well-written---clear and articulate; few or no typos; not too long| Moderately well-written; some typos; wordy or vague| Unclear, awkward, or imprecise writing; numerous typos; too long and wordy or too short and vague\\

____________
____________

#### Peer evaluation form (end of semester)

##### Name/team \#/Poster Title: 
<br>
<br>
<br>



Please assign scores that reflect how you really feel about the extent to which the other members of your team contributed to your learning and/or your team's performance. This will be your only opportunity to reward the members of your team who worked hard on your behalf. (Note: If you give everyone pretty much the same score, you will be hurting those who did the most and helping those who did the least.)

**Instructions:** In the space below, please rate each of the other members of your team. Each member's peer evaluation score will be the average of the points they receive from the other members of the team. To complete the evaluation you should: 1) List the name of each member of your team in the alphabetical order of their last names and, 2) assign an average of ten points to the other members of your team and, 3) differentiate some in your ratings; for example, you must give at least one score of 11 or higher (maximum = 15) and one score of 9 or lower.


Rank | Team member | Score
-----|--------------------|----------|
1 |  | 
2|   |   
3|    |
4|    |


**Additional feedback**

Please briefly describe the reasons for your highest and lowest ratings in the space below. These comments will be shared anonymously. Note: Your comments should be descriptive, not evaluative; as clear and specific as possible; phrased in constructive terms; and focused on areas in which the student has made especially valuable contributions or could improve in the future. 

Reason(s) for your highest rating(s):

<br>
<br>
<br>
<br>
<br>
<br>

Reason(s) for your lowest rating(s):
<br>
<br>
<br>
<br>
<br>
<br>









