---
title: "Team Assignments"
author: "Jacob Montgomery"
date: "September 24, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Team Assignment

Team number | Member 1 | Membeer 2 | Member 3 | Member 4 | Member 5
:------:|:------:|:------:|:------:|:------:|:------:
1 | Kelly Ryan | William Scerpella | Henry Nguyen | Sydney Welter
2 | Ashlee Chung | Aliza Astrow | Nicole Ferzoco | Nathan Praeger
3 | Ilana Engel | Kalen Davison | Nate Lowis | Kristen Lau
4 | Stephanie Wright | Monye Pitt | Andrew Englund | Jack Broitman
5 | Joey Vettiankal | Hannah Schanzer | Sydney Curtis | Amanda Mendelsohn
6 | Claire Thomas | Carter Paterson | Rishi Patel | Pilar Gonzalez
7 | Camilo Haller | Mikaela Adwar | Emily Garner | Massil Adnani
8 | Drew McPike | Josh LaFianza | Giulia Neaher | Nicholas Castriz
9 | Noah Gordon | David McGarr | Joe Gorman
10 | Zach Vincent | Aidan Strassmann | Tom Hutchison | Andrea Tam | Zachary Virgilio 
11 | Shreya Tripathy | Brian Adler | Hannah Daniels | Jack Ploshnick | Alex Cheung
12 | Robert Stoffa | Joel Brown | Kevin Si | Serina Karkhanis
13 | Jon Wingens | Dugan Marieb | Sarah Paul | Carolyn Perlmutter
