---
title: "Version control and minimum commenting"
author: |
  | Jacob M. Montgomery
  | *Washington University in St. Louis*
  | *Department of Politcal Science*
date: '2020'
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
#   beamer_presentation: default
#   slidy_presentation: default


---


## Orientation for today

**Last time**

1. Functions 
    
<br>



--

**Today**

1. Version control/documentation
    + Getting up on github
    + Helping your future self

--

**Next class**

1. Debugging
2. Testing
3. Profiling


---


# Why version control?


Have you ever ... (Source: Stack overflow)
- Made a change to code, realised it was a mistake and wanted to revert back?
- Lost code or had a backup that was too old?
- Had to maintain multiple versions of a product?
- Wanted to see the difference between two (or more) versions of your code?
- Wanted to prove that a particular change broke or fixed a piece of code?
- Wanted to review the history of some code?

--

- Wanted to submit a change to someone else's code?
- Wanted to share your code, or let other people work on your code?
- Wanted to see how much work is being done, and where, when and by whom?
- Wanted to experiment with a new feature without interfering with working code?


---

## There's no way to learn this but to do it

- Install Git: http://git-scm.com/book/en/Getting-Started-Installing-Git
- Sign up for GitHub
- Install the GUI
    + http://mac.github.com/
    + http://windows.github.com/

--

- Clone this repository to your computer - https://github.com/jmontgomery/Class.git


---

## As a group: Committing, syncing, reverting

- Fork the code to a new repository (https://help.github.com/articles/fork-a-repo)
- Edit the code
- Sync the changes
- On a different machine, sync the changes
- Make new changes and commit/sync
- Now revert it back one commit


---

## Branching/merging

- Make a branch
- Add a new file to the new branch
- Edit the original file in the new branch
- Merge the branches back together


--- 

## Conflict management

- Everyone sync back up
- Make yet another new branch
- Add a new file to the new branch
- Edit the original file in the new branch so that now they don't have the same code
- Merge the branches back together and resolve the conflicts


---

## Misc

- .gitignore
- Issues
- Command line
- Complex files


---

# A Comment on comments

- You should put in lot's of comments explaining to yourself what each chunk of code does
- Functions are extra important to document
- Functions should come with:
    + Short name of the function
    + A sentence or two about what it does
    + Input parameter expected
    + Description of the output
    + Author information (optional)



---

## Example


```{r}
##
# Function for comparing multiple models based on pred. performance
#
# This function produces statistics to compare the predictive 
# performance of the different models component models, as well as 
# for the EBMA model itself, for either the calibration or the test period.
#
# .forecastData - An object of class 'ForecastData'. 
# .period - Can take value of "calibration" or "test" and indicates 
# the period for which the test statistics should be calculated.
# .fitStatistics - A vector naming statistics that should be calculated.  
# .threshold - The threshold used to calculate when a "positive" prediction 
# is made by the model for binary dependent variables.
#
# Returns a data object of the class 'CompareModels' with the following slots: 
# fitstatistic, period, threshold
```


---

## Problem Set 2

- You will fork Dom's repo
- You will edit your code and let her know when you are "done."
- This is ``social coding'' so you can look at other forks.
- Part of your grade will be in examining your documentation, and your use of versioning.  Play around with the possibilities.  


