# Version Control

## Why version control?

Have you ever ... (Source: Stack overflow)
- Made a change to code, realised it was a mistake and wanted to revert back?
- Lost code or had a backup that was too old?
- Had to maintain multiple versions of a product?
- Wanted to see the difference between two (or more) versions of your code?
- Wanted to prove that a particular change broke or fixed a piece of code?
- Wanted to review the history of some code?
- Wanted to submit a change to someone else's code?
- Wanted to share your code, or let other people work on your code?
- Wanted to see how much work is being done, and where, when and by whom?
- Wanted to experiment with a new feature without interfering with working code?

## Setup

- Install Git: http://git-scm.com/book/en/Getting-Started-Installing-Git
- Sign up for GitHub
- Install the GUI
    + http://mac.github.com/
    + http://windows.github.com/

## Workflow

Every time you work on a group project that is stored in git, you should pull right away, do your work, then commit and push immediately.
I recommend doing this workflow every time you make a significant change or start working on something else. It backs up your work so that 
you can go back to an earlier version in case you mess something up later.

### Pull

This updates your repository to the newest version so that when other people on your team make changes, you will be able to have the most recently
updated version of the code/repository.

### Commit

This is step 1 of adding your changes to GitHub (push is step 2). Committing your changes requires that you specify which changed files you want 
to commit as well as a brief commit message summarizing what you changed since the last commit.

### Push

This is step 2 of adding your changes to GitHub. You can think of committimg as wrapping up a gift that you made and pushing is mailing it to the recipient.
They don't "open" the gift until they Pull and see what you pushed. Pushing uploads all un-pushed commits to GitHub so that you can see them
in GitHub desktop as well as your repository online. 

## Branches

Large software projects use branches to have a production environment that is always working, and other branches for new feature development.
Once a feature is ready, the development branch can be merged with the production branch (typically master). You'll have to manually choose which
version of each file to keep.

## Forking

If you see someone's repository and want to copy it and make your own changes without affecting their repository (and potentially without them even knowing),
you can "fork" the repository. This gives you your own copy of it to mess with as you please.

## Reverting

If you make a mistake and commit and push it (or your team member does), you can revert to a prior commit. This is why it's super useful
to commit and push regulary!!! You can revert from any commit which will set your current repository state back to exactly what it looked 
like at that exact moment in time.