---
title: "Lecture 6: Calculating probabilities"
author: "Jacob M. Montgomery"
date: "Quantitative Political Methodology"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```





# Lecture 6: Calculating probabilities

----

## IPA

Let's try this



-----

## Roadmap

Last time: 

- Understanding the concept of a sampling distribution
- Understand the concept of a standard error
- See how the CLT allows us to know the distribution of certain sample statistics

This time:

- How to find probabilities from a binomial table
- How to find probabilities using a Z-distribution table
- How to find "critical values."
- Extend this logic to the t-distribution (online only)




----

### Motivation

#### Castenedat v. Partida

- The true number of Mexican-Americans was 79.1\% of the population.
- Individuals were selected for jury participation using the ``key man'' system.
- 45.5\% of the members of the grand jury were Mexican-American.

\pause

How likely was this to happen by chance if the jury was of size $n=60$?  

-----

### Question 1

Which fraction represents the probability of obtaining exactly eight heads in ten tosses of a fair coin? 


----

### Question 2

For a normal distribution with $\mu = 50$ and $\sigma = 3$, find the probability that an observation falls:

1. At or below the value of 56
2. Between the values of 45 and 56



-----

### Question 3

Suppose that for exam grades $\mu$ = 75 and $\sigma$ = 15. 

1. What is the probability of receiving an exam grade of 90 or better?
2. What about a 60 or worse?
3. If the probability of doing better than you is .05, then what is  your score?  

----

### Question 4 (not on your form)


If you have a t-distributed variable with 21 degrees of freedom.

- What is the probability of a value above 1.721?
- .05\% of the distribution is greater than what critical value?

